steps:

# CONTAINERIZE: containerize the application
- name: gcr.io/cloud-builders/docker
  entrypoint: docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello', '.']

# PUSH: push container image to registry
- name: gcr.io/cloud-builders/docker
  entrypoint: docker
  args: ['push','gcr.io/$PROJECT_ID/hello']